version: '2'
services:
    assetsmgmt-app:
        image: assetsmgmt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://assetsmgmt-mysql:3306/assetsmgmt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    assetsmgmt-mysql:
        extends:
            file: mysql.yml
            service: assetsmgmt-mysql
